// Code generated by protoc-gen-go. DO NOT EDIT.
// source: User.proto

package protocol

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CashType int32

const (
	CashType_UNKNOWN      CashType = 0
	CashType_RECHARGE     CashType = 1
	CashType_DEDUCT_MONEY CashType = 2
	CashType_ADD_GOLD     CashType = 3
	CashType_PAYOUT       CashType = 4
)

var CashType_name = map[int32]string{
	0: "UNKNOWN",
	1: "RECHARGE",
	2: "DEDUCT_MONEY",
	3: "ADD_GOLD",
	4: "PAYOUT",
}

var CashType_value = map[string]int32{
	"UNKNOWN":      0,
	"RECHARGE":     1,
	"DEDUCT_MONEY": 2,
	"ADD_GOLD":     3,
	"PAYOUT":       4,
}

func (x CashType) String() string {
	return proto.EnumName(CashType_name, int32(x))
}

func (CashType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{0}
}

//现金操作请求
type CashOperRequest struct {
	HallId               int32    `protobuf:"varint,1,opt,name=hall_id,json=hallId,proto3" json:"hall_id,omitempty"`
	AgentId              int32    `protobuf:"varint,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	UserId               int64    `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	HallName             string   `protobuf:"bytes,4,opt,name=hall_name,json=hallName,proto3" json:"hall_name,omitempty"`
	UserName             string   `protobuf:"bytes,5,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Amount               float64  `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Type                 CashType `protobuf:"varint,7,opt,name=type,proto3,enum=protocol.CashType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CashOperRequest) Reset()         { *m = CashOperRequest{} }
func (m *CashOperRequest) String() string { return proto.CompactTextString(m) }
func (*CashOperRequest) ProtoMessage()    {}
func (*CashOperRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{0}
}

func (m *CashOperRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CashOperRequest.Unmarshal(m, b)
}
func (m *CashOperRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CashOperRequest.Marshal(b, m, deterministic)
}
func (m *CashOperRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CashOperRequest.Merge(m, src)
}
func (m *CashOperRequest) XXX_Size() int {
	return xxx_messageInfo_CashOperRequest.Size(m)
}
func (m *CashOperRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CashOperRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CashOperRequest proto.InternalMessageInfo

func (m *CashOperRequest) GetHallId() int32 {
	if m != nil {
		return m.HallId
	}
	return 0
}

func (m *CashOperRequest) GetAgentId() int32 {
	if m != nil {
		return m.AgentId
	}
	return 0
}

func (m *CashOperRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *CashOperRequest) GetHallName() string {
	if m != nil {
		return m.HallName
	}
	return ""
}

func (m *CashOperRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *CashOperRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CashOperRequest) GetType() CashType {
	if m != nil {
		return m.Type
	}
	return CashType_UNKNOWN
}

//现金操作响应
type CashOperResponse struct {
	ResultCode           int32    `protobuf:"varint,1,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	Desc                 string   `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Restult              *Result  `protobuf:"bytes,3,opt,name=restult,proto3" json:"restult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CashOperResponse) Reset()         { *m = CashOperResponse{} }
func (m *CashOperResponse) String() string { return proto.CompactTextString(m) }
func (*CashOperResponse) ProtoMessage()    {}
func (*CashOperResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{1}
}

func (m *CashOperResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CashOperResponse.Unmarshal(m, b)
}
func (m *CashOperResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CashOperResponse.Marshal(b, m, deterministic)
}
func (m *CashOperResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CashOperResponse.Merge(m, src)
}
func (m *CashOperResponse) XXX_Size() int {
	return xxx_messageInfo_CashOperResponse.Size(m)
}
func (m *CashOperResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CashOperResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CashOperResponse proto.InternalMessageInfo

func (m *CashOperResponse) GetResultCode() int32 {
	if m != nil {
		return m.ResultCode
	}
	return 0
}

func (m *CashOperResponse) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *CashOperResponse) GetRestult() *Result {
	if m != nil {
		return m.Restult
	}
	return nil
}

type Result struct {
	Amount               float64  `protobuf:"fixed64,1,opt,name=amount,proto3" json:"amount,omitempty"`
	OrderSn              string   `protobuf:"bytes,2,opt,name=order_sn,json=orderSn,proto3" json:"order_sn,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_979821478719c248, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Result) GetOrderSn() string {
	if m != nil {
		return m.OrderSn
	}
	return ""
}

func init() {
	proto.RegisterEnum("protocol.CashType", CashType_name, CashType_value)
	proto.RegisterType((*CashOperRequest)(nil), "protocol.CashOperRequest")
	proto.RegisterType((*CashOperResponse)(nil), "protocol.CashOperResponse")
	proto.RegisterType((*Result)(nil), "protocol.Result")
}

func init() { proto.RegisterFile("User.proto", fileDescriptor_979821478719c248) }

var fileDescriptor_979821478719c248 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0xe7, 0x35, 0x4b, 0xd2, 0xd7, 0x09, 0xac, 0x77, 0x80, 0x76, 0x1c, 0x88, 0x7a, 0x40,
	0xd1, 0x0e, 0x15, 0x2a, 0x47, 0x4e, 0x55, 0x53, 0x6d, 0x15, 0x90, 0x0c, 0xd3, 0x0a, 0xed, 0x14,
	0x85, 0xfa, 0x89, 0x21, 0xa5, 0x71, 0xb0, 0x9d, 0xc3, 0xfe, 0x53, 0xfe, 0x1c, 0x64, 0xb7, 0xd1,
	0x56, 0x69, 0xa7, 0xe4, 0xfb, 0x7e, 0x7e, 0xf6, 0xfb, 0xde, 0x03, 0xd8, 0x1a, 0xd2, 0xb3, 0x56,
	0x2b, 0xab, 0x30, 0xf6, 0x9f, 0x9d, 0xaa, 0xa7, 0xff, 0x18, 0xbc, 0x5e, 0x56, 0xe6, 0xa1, 0x68,
	0x49, 0x0b, 0xfa, 0xdb, 0x91, 0xb1, 0xf8, 0x16, 0xa2, 0x87, 0xaa, 0xae, 0xcb, 0x3f, 0x72, 0xcc,
	0x12, 0x96, 0x5e, 0x88, 0xd0, 0xc9, 0xb5, 0xc4, 0x09, 0xc4, 0xd5, 0x6f, 0x6a, 0xac, 0x23, 0xe7,
	0x9e, 0x44, 0x5e, 0xaf, 0xa5, 0xab, 0xe9, 0x0c, 0x69, 0x47, 0x06, 0x09, 0x4b, 0x07, 0x22, 0x74,
	0x72, 0x2d, 0xf1, 0x1d, 0x0c, 0xfd, 0x65, 0x4d, 0xb5, 0xa7, 0x71, 0x90, 0xb0, 0x74, 0x28, 0x62,
	0x67, 0xe4, 0xd5, 0x9e, 0x1c, 0xf4, 0x55, 0x1e, 0x5e, 0x1c, 0xa0, 0x33, 0x3c, 0x7c, 0x03, 0x61,
	0xb5, 0x57, 0x5d, 0x63, 0xc7, 0x61, 0xc2, 0x52, 0x26, 0x8e, 0x0a, 0x3f, 0x40, 0x60, 0x1f, 0x5b,
	0x1a, 0x47, 0x09, 0x4b, 0x5f, 0xcd, 0x71, 0xd6, 0x67, 0x99, 0xb9, 0x1c, 0x9b, 0xc7, 0x96, 0x84,
	0xe7, 0x53, 0x03, 0xfc, 0x29, 0x99, 0x69, 0x55, 0x63, 0x08, 0xdf, 0xc3, 0x48, 0x93, 0xe9, 0x6a,
	0x5b, 0xee, 0x94, 0xa4, 0x63, 0x3c, 0x38, 0x58, 0x4b, 0x25, 0x09, 0x11, 0x02, 0x49, 0x66, 0xe7,
	0xe3, 0x0d, 0x85, 0xff, 0xc7, 0x6b, 0x88, 0x34, 0x19, 0xdb, 0xd5, 0xd6, 0x67, 0x1b, 0xcd, 0xf9,
	0xd3, 0x9b, 0xc2, 0x97, 0x8a, 0xfe, 0xc0, 0xf4, 0x33, 0x84, 0x07, 0xeb, 0x59, 0xfb, 0xec, 0xa4,
	0xfd, 0x09, 0xc4, 0x4a, 0x4b, 0xd2, 0xa5, 0x69, 0x8e, 0xaf, 0x44, 0x5e, 0xff, 0x68, 0xae, 0xbf,
	0x43, 0xdc, 0x67, 0xc0, 0x11, 0x44, 0xdb, 0xfc, 0x4b, 0x5e, 0xfc, 0xcc, 0xf9, 0x19, 0x5e, 0x42,
	0x2c, 0x56, 0xcb, 0xdb, 0x85, 0xb8, 0x59, 0x71, 0x86, 0x1c, 0x2e, 0xb3, 0x55, 0xb6, 0x5d, 0x6e,
	0xca, 0x6f, 0x45, 0xbe, 0xba, 0xe7, 0xe7, 0x8e, 0x2f, 0xb2, 0xac, 0xbc, 0x29, 0xbe, 0x66, 0x7c,
	0x80, 0x00, 0xe1, 0xdd, 0xe2, 0xbe, 0xd8, 0x6e, 0x78, 0x30, 0xbf, 0x83, 0xc0, 0xed, 0x1d, 0x6f,
	0x61, 0xd8, 0x0f, 0xa3, 0xc2, 0xc9, 0xe9, 0xcc, 0x9e, 0xed, 0xfe, 0xea, 0xea, 0x25, 0x74, 0x18,
	0xde, 0xf4, 0x2c, 0x65, 0x1f, 0xd9, 0xaf, 0xd0, 0x1f, 0xf8, 0xf4, 0x3f, 0x00, 0x00, 0xff, 0xff,
	0xc6, 0xef, 0x61, 0x00, 0x50, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	CashOpera(ctx context.Context, opts ...grpc.CallOption) (User_CashOperaClient, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) CashOpera(ctx context.Context, opts ...grpc.CallOption) (User_CashOperaClient, error) {
	stream, err := c.cc.NewStream(ctx, &_User_serviceDesc.Streams[0], "/protocol.User/CashOpera", opts...)
	if err != nil {
		return nil, err
	}
	x := &userCashOperaClient{stream}
	return x, nil
}

type User_CashOperaClient interface {
	Send(*CashOperRequest) error
	Recv() (*CashOperResponse, error)
	grpc.ClientStream
}

type userCashOperaClient struct {
	grpc.ClientStream
}

func (x *userCashOperaClient) Send(m *CashOperRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *userCashOperaClient) Recv() (*CashOperResponse, error) {
	m := new(CashOperResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	CashOpera(User_CashOperaServer) error
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) CashOpera(srv User_CashOperaServer) error {
	return status.Errorf(codes.Unimplemented, "method CashOpera not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_CashOpera_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(UserServer).CashOpera(&userCashOperaServer{stream})
}

type User_CashOperaServer interface {
	Send(*CashOperResponse) error
	Recv() (*CashOperRequest, error)
	grpc.ServerStream
}

type userCashOperaServer struct {
	grpc.ServerStream
}

func (x *userCashOperaServer) Send(m *CashOperResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *userCashOperaServer) Recv() (*CashOperRequest, error) {
	m := new(CashOperRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.User",
	HandlerType: (*UserServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CashOpera",
			Handler:       _User_CashOpera_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "User.proto",
}
